Feature/fp 2
Holmsbergsviti/findPair pull request #3
Opened 2022-06-21 16:18 UTC by Holmsbergsviti

Added using random images

2022-06-22 22:51 UTC, specter-kr2 requested changes

2022-06-22 22:51 UTC, vlad-nam commented on Index.html
> +            var i = 0;
I'd like to recommend to avoid using _var_ and use _const_ and _let_ instead.
You can read [this article](https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/) to understand the difference if you need more explanation you can just DM me

2022-06-22 22:51 UTC, vlad-nam commented on Index.html
> +        <script>
Let's move JS code to separate javascript file?

2022-06-22 22:51 UTC, vlad-nam commented on Index.html
> +            var a = 0;
let's change the name of variable and make it more convenient. It's more important to have special names to understand the meaning when we read it

2022-06-22 22:51 UTC, vlad-nam commented on Index.html
> +            var b = 0;
the same as above

2022-06-22 22:51 UTC, vlad-nam commented on Index.html
> +            var old_text = "";
in JavaScript we usually use camelCase for names, try to have the same style for all names

2022-06-22 22:51 UTC, vlad-nam commented on Index.html
> +                'Coin1', 'Dog', 'Dog1', 'Fish', 'Fish1', 'Telephone', 'Telephone1'];
It's nice solution to add _1_ but it add some mess to the code. Try to think before coding how we can keep only original names and we can discuss it

2022-06-22 22:51 UTC, vlad-nam commented on Index.html
> +                    if (textIdIMg !== old_text) {
Let's try to think how we can avoid code block duplication inside this _if_ and inside other _if_'s like that

2022-06-27 13:42 UTC, Holmsbergsviti commented on Index.html
> +            var i = 0;
Done

2022-06-27 13:42 UTC, Holmsbergsviti commented on Index.html
> +        <script>
Done

2022-06-27 13:43 UTC, Holmsbergsviti commented on Index.html
> +            var a = 0;
Done

2022-06-27 13:43 UTC, Holmsbergsviti commented on Index.html
> +            var b = 0;
Done

2022-06-27 13:43 UTC, Holmsbergsviti commented on Index.html
> +            var old_text = "";
Done

2022-06-27 13:45 UTC, Holmsbergsviti commented on Index.html
> +                    if (textIdIMg !== old_text) {
Done

2022-06-27 13:48 UTC, Holmsbergsviti commented on Index.html
> +                'Coin1', 'Dog', 'Dog1', 'Fish', 'Fish1', 'Telephone', 'Telephone1'];
Done, new algorithm in PR: https://github.com/Holmsbergsviti/findPair/pull/4

2022-06-28 07:04 UTC, merged